# Generated by Django 4.0.3 on 2022-12-29 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passcode', '0004_alter_answer_author_alter_question_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
